# Generated by Django 2.0.9 on 2018-11-03 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.TextField()),
                ('run', models.CharField(max_length=200)),
                ('nombre', models.TextField()),
                ('fechanac', models.DateTimeField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=200)),
                ('region', models.TextField()),
                ('ciudad', models.TextField()),
                ('tipo', models.TextField()),
                ('fechasol', models.DateTimeField(default=datetime.datetime(2018, 11, 3, 23, 2, 20, 817666, tzinfo=utc))),
            ],
        ),
    ]
